### ISSUE TITLE
did it support codetyphon？

### ISSUE THREAD

**Issue by k4n5ha0** [VuceticBranislav/era-modern#1]
did it support Compile with codetyphon？
thx ：-）

**Comment by VuceticBranislav** [comment]
I am not familiar with codetyphon. If codetyphon can compile classics delphi 11 dll projects then there should be no problems. Keep in mind that i use pre-build and post-build events.

Compile steps:
1. Compile BuildTools first,
2. Use BuildTools to generate VersionInfo.res in pre-build event,
3. Build project,
4. Use BuildTools to generate map file in post-build event,
Repeat steps 2-4 for Era and Vfs project.
